# Algebraic Groups of Simple Neural Networks 
** November 2017 **

** Andrew Riberio @ [AndrewRib.com](http://www.andrewrib.com) **

In this notebook we will use a custom library, HeftyNumber, to enumerate the solution space.

Install HeftyNumber by:
```
pip install git+git://github.com/Andrewnetwork/HeftyNumber
```

** Note: ** This notebook contains interactive elements and certain latex snippets that will not render in github markdown. 
You must run this notebook on your local Jupyter notebook environment for interactive elements or render or if you wish to render just the latex by using the url of this repo with the [online NBViewer](https://nbviewer.jupyter.org/).

## Libraries

In [2]:
import numpy as np
from HeftyNumber.HeftyNumber import HeftyNumber
from HeftyNumber.MatrixCount import MatrixCount

## Core Functions

In [3]:
def relu(z):
    return np.maximum(0,z)

def linLayer(x,w,b):
    return x.T*w + b

def fullNetwork(x,W,c,w,b):
    h = relu( linLayer(W,x,c) )
    return linLayer(w, h, b)

## Experiment 1: Exploring AND solutions
$$
\begin{bmatrix} 
0 & 0 \\
0 & 1 \\
1 & 0 \\
1 & 1 \\
\end{bmatrix}
\overset{∧}{\rightarrow}
\begin{bmatrix} 
0  \\
0 \\
0  \\
1  \\
\end{bmatrix}
$$

$$
w^\intercal 
relu(\begin{bmatrix} 
0 & 0 \\
0 & 1 \\
1 & 0 \\
1 & 1 \\
\end{bmatrix}^\intercal 
W + c)+b = \begin{bmatrix} 0 & 0 & 0 & 1 \end{bmatrix}^\intercal
$$

In our previous notbook we computed by hand the following solution:

We will now explore alternative solutions by enumerating the possible integer valued matricies. We begin be holding all but W constant and try to find alternative values for W that still solves the problem. 

In [4]:
def uniqueMat(matrix):
    tmp = []
    for c in matrix:
        skip = False
        for elm in tmp:
            if(np.array_equal(c,elm)):
                skip = True
                break;
        if not skip:
            tmp.append(c)
            
    return tmp

In [13]:
# x: 2 by 4
# W: 2 by 2
# c: 2 by 1
# w: 2 by 1
# b: scalar

target = np.matrix([[0,0,0,1]])

def getValidW(x,c,w,b,base):
    wPerm = MatrixCount.permGroup((2,2),base)
    
    validW = []

    #print("Valid W matricies:\n")
    #print("Base:{0}".format(base))
    for W in wPerm:
        res = fullNetwork(x,W,c,w,0)
        if(np.array_equal(res,target)):
            a = HeftyNumber(W.flatten(),base)
            validW.append(W)
            #print(W.flatten())
            #print(format(a.b10()))

    #print("Number of valid W: {0}".format(len(validW)) )
    return validW

def getValidC(x,validW,w,b,base):
    shape = (1,2)
    cPerm = MatrixCount.permGroup(shape,base)
    cGroup = []

    for i in reversed(cPerm):
        cGroup.append(i)
    for i in cPerm:
        if(not np.array_equal(i,np.zeros(shape))):
            cGroup.append(i*-1)

    validC = []
    for W in validW:
        for c in cGroup:
            res = fullNetwork(x,W,c.T,w,0)
            if(np.array_equal(res,target)):
                a = HeftyNumber(W.flatten(),base)
                validC.append([W,c])


    validC = uniqueMat(validC)
    
    return validC

def getValidw(x,validW,c,b,base):
    shape = (1,2)
    wPerm = MatrixCount.permGroup(shape,base)
    wGroup = []

    for i in reversed(wPerm):
        wGroup.append(i)
    for i in wPerm:
        if(not np.array_equal(i,np.zeros(shape))):
            wGroup.append(i*-1)

    validw = []
    for W in validW:
        for w in wGroup:
            res = fullNetwork(x,W,c,w.T,0)
            if(np.array_equal(res,target)):
                a = HeftyNumber(W.flatten(),base)
                validw.append([W,w])

    validw = uniqueMat(validw)
    
    return validw


In [14]:
x = np.matrix([[0,0,1,1],[0,1,0,1]])
c = np.matrix([0,-1]).T
w = np.matrix([0,1]).T
W = np.matrix([[0,1],[0,1]])
b = 0
base = 2

vW = getValidW(x,c,w,b,base)
vc = getValidC(x,vW,w,b,base)
vw = getValidw(x,vW,c,b,base)

In [19]:
for i in vW:
    print(i)

[[0 1]
 [0 1]]
[[0 1]
 [1 1]]
[[1 1]
 [0 1]]
[[1 1]
 [1 1]]


In [ ]:
vw2 = getValidW(x,vc[3][1].T,w,b,base)
vc2 = getValidC(x,vw2,w,b,base)

In [ ]:
for i in vc2:
    a = HeftyNumber(i[0].flatten(),base)
    b = HeftyNumber(i[1].flatten(),base)

    print(a.b10(),b.b10())
    #print(i[0],i[1])

In [ ]:
for i in vc2:
    a = HeftyNumber(i[0].flatten(),base)
    b = HeftyNumber(i[1].flatten(),base)

    print(a.b10(),b.b10())
    #print(i[0],i[1])

In [ ]:
def fn3(n):
    return (n)*(n+1)
def fn2(n):
    summ = 0
    for i in range(1,n+1):
        summ += 2*i
    return summ
def b(n):
    return 10+5*n+n*(n+1)

In [ ]:
#Starts at 3
def k(b):
    b = b-3
    return 10+5*b+b*(b+1)

def g(b):
    n = b-3
    return 9+7*(b-3)+n*(n-1)

def permGroup(b):
    B_R = A_R = range(0,b)
    start = k(b)
    res = 0 
    for A in A_R:
        for B in B_R:
            res = start+(b*B)+(g(b)*b)*A
            print(res)

$$
10+5b+b*(b+1) + bB+(9+7*(b-3)+(b-3)*(b-4))A
$$

In [ ]:
permGroup(9)

In [54]:
f = MatrixCount.permGroup((3,3),2)
for i in f:
    print(i)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 1]]
[[0 0 0]
 [0 0 0]
 [0 1 0]]
[[0 0 0]
 [0 0 0]
 [0 1 1]]
[[0 0 0]
 [0 0 0]
 [1 0 0]]
[[0 0 0]
 [0 0 0]
 [1 0 1]]
[[0 0 0]
 [0 0 0]
 [1 1 0]]
[[0 0 0]
 [0 0 0]
 [1 1 1]]
[[0 0 0]
 [0 0 1]
 [0 0 0]]
[[0 0 0]
 [0 0 1]
 [0 0 1]]
[[0 0 0]
 [0 0 1]
 [0 1 0]]
[[0 0 0]
 [0 0 1]
 [0 1 1]]
[[0 0 0]
 [0 0 1]
 [1 0 0]]
[[0 0 0]
 [0 0 1]
 [1 0 1]]
[[0 0 0]
 [0 0 1]
 [1 1 0]]
[[0 0 0]
 [0 0 1]
 [1 1 1]]
[[0 0 0]
 [0 1 0]
 [0 0 0]]
[[0 0 0]
 [0 1 0]
 [0 0 1]]
[[0 0 0]
 [0 1 0]
 [0 1 0]]
[[0 0 0]
 [0 1 0]
 [0 1 1]]
[[0 0 0]
 [0 1 0]
 [1 0 0]]
[[0 0 0]
 [0 1 0]
 [1 0 1]]
[[0 0 0]
 [0 1 0]
 [1 1 0]]
[[0 0 0]
 [0 1 0]
 [1 1 1]]
[[0 0 0]
 [0 1 1]
 [0 0 0]]
[[0 0 0]
 [0 1 1]
 [0 0 1]]
[[0 0 0]
 [0 1 1]
 [0 1 0]]
[[0 0 0]
 [0 1 1]
 [0 1 1]]
[[0 0 0]
 [0 1 1]
 [1 0 0]]
[[0 0 0]
 [0 1 1]
 [1 0 1]]
[[0 0 0]
 [0 1 1]
 [1 1 0]]
[[0 0 0]
 [0 1 1]
 [1 1 1]]
[[0 0 0]
 [1 0 0]
 [0 0 0]]
[[0 0 0]
 [1 0 0]
 [0 0 1]]
[[0 0 0]
 [1 0 0]
 [0 1 0]]
[[0 0 0]
 [1 0 0]
 [

In [51]:
a=[]
a.append(np.matrix([1,0]))
a.append(np.matrix([0,1]))
a.append(np.matrix([1,1]))
#a.append(np.matrix([0,0]))

for i in a:
    for b in a:
        print(i.T*b)

[[1 0 1]
 [0 0 0]
 [1 0 1]]
[[0 1]
 [0 0]
 [0 1]]
[[1 1]
 [0 0]
 [1 1]]
[[0 0 0]
 [1 0 1]]
[[0 0]
 [0 1]]
[[0 0]
 [1 1]]
[[1 0 1]
 [1 0 1]]
[[0 1]
 [0 1]]
[[1 1]
 [1 1]]


In [65]:
def rep(m):
    for i in m:
        i[i==2]=3
        
    return m

a = [np.matrix([1,2,3,4,5])]

rep(a)

print(a)

[matrix([[1, 3, 3, 4, 5]])]


5*5

In [73]:
7*7

49

In [47]:
b.T*c

matrix([[0, 0],
        [1, 1]])