<center>
    <h1>Automata Seedlings</h1>
    <h2>Andrew Ribeiro</h2>
    <h3>July 21, 2016</h3>
</center>

<center> A new way of looking at one-shot machine learning. What's it like to become something? It is as it permiates me.</center>
<hr />


In [48]:
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx

Ordering/Naming convention: From left to right, top to bottom.

In [7]:
A = np.matrix('0 1 0 0;\
               1 1 1 1;\
               0 1 0 1')

B = np.matrix('0 1 1;\
               1 1 0')

A_named = np.matrix('0 2 0 0;\
                     1 3 5 6;\
                     0 4 0 7')

B_named = np.matrix('0 2 4;\
                     1 3 0')

In [288]:
class Tree: 
    identity = None
    children = []
    
    def nChildren(self):
        len(children)
        
    def addChild(self, child):
        self.children.append(child)
        
    # Find the parent node and add the child. 
    def addChildToNode(self, parent, child):
        found = False
        
        for chld in self.children:
            # If we found the child that is the parent being added to. 
            if chld.identity == parent.identity:
                chld.addChild(child)
                found = True
                break
                
        if not found: 
            # None of our children are the parent. Search our childrent's 
            # children for the parent of this orphan child. 
            for chld in children:
                self.addChildToNode(chld, child)
                
    def __init__(self,ident):
        self.setI(ident)
    
    def setI(self, ident):
        self.identity = ident

class Node:
    identity = None
    children = []
    
    def __init__(self,ident):
        self.setI(ident)
        
    def setI(self, ident):
        self.identity = ident
        
    def addChild(self, child):
        self.children.append(Node(child))
    
    def append( self , child):
        self.children.append(child)

In [133]:
a = Tree(1)
a.addChild(Node(2))



In [134]:
def printNode:
    None

SyntaxError: invalid syntax (<ipython-input-134-5957d712d9c7>, line 1)

In [323]:

    
def mapTopology(matrix, startingNode):
    False

def walkMatrix( matrix ,parentRow,parentCol, location):
    t = Node(matrix[location])
    
    print( matrix[location] )
    
    return t  

def adjacentNodes( matrix, location ):
    
    element = matrix[location]
    
    row = location[0]
    col = location[1]
    
    maxRows = matrix.shape[0]
    maxCols = matrix.shape[1]
    
    if element > 0: 
        t = Node( element )
        ## Find Adjacency ##

        # Left
        if (col-1) >= 0  and (row-1) >= 0 and matrix[row-1,col-1] > 0:
            # Left Top 
            t.addChild( walkMatrix(matrix, row, col, (row-1,col-1) ) )
        if (col-1) >= 0 and matrix[row,col-1] > 0:
            # Left Middle
            t.addChild( walkMatrix(matrix, row, col, (row,col-1) ) )
        if (col-1) >= 0 and (row+1) < maxRows and matrix[row+1,col-1] > 0:
            # Left Bottom
            t.addChild(walkMatrix(matrix,row, col, (row+1,col-1)))

        # Middle
        if (row-1) >=0 and matrix[row-1,col] > 0:
            # Up
            t.addChild( walkMatrix(matrix,row, col, (row-1,col)) )
        if (row+1) < maxRows and matrix[row+1,col] > 0:
            # Down
            t.addChild( walkMatrix(matrix,row, col, (row+1,col)) )

        # Right 
        if  (col+1) < maxCols  and (row-1) >= 0 and matrix[row-1,col+1] > 0:
            # Right Top 
            t.addChild( walkMatrix(matrix,row, col, (row-1,col+1)) )
        if  (col+1) < maxCols and matrix[row,col+1] > 0:
            # Right Middle
            t.addChild( walkMatrix(matrix,row, col, (row,col+1)) )
        if (col+1) < maxCols and (row+1) < maxRows and matrix[row+1,col+1] > 0:
            # Right Bottom
            t.addChild(walkMatrix(matrix,row, col, (row+1,col+1)))
        
        return t
    
    
# adjacencyConnectedNodes (ACN)
def ACN( matrix ):
    # Itterate through by column. 
    
    maxRows = matrix.shape[0]
    maxCols = matrix.shape[1]
    nodes = []
    
    for col in range( maxCols ):
        for row in range( maxRows ):
            
            element = matrix[row,col]
            
            # Make sure it's not a blank cell"and matrix[row,col] > 0"
            # Add adjacent nodes from top left to bottom right. 
            if element > 0: 
                print("Parent Tree: "+str( element ) )
                
                ## Find Adjacency ##
                nodes.append( adjacentNodes(matrix, (row,col)) )
            
    return nodes

In [322]:
print(B_named )

b= ACN(B_named)

print( "Length of : "+ str( len(b) ) );

## 00 -> 10 -> 01 -> 11

[[0 2 4]
 [1 3 0]]
Parent Tree: 1
2
3
Parent Tree: 2
1
3
4
Parent Tree: 3
1
2
4
Parent Tree: 4
2
3
Length of : 4


In [314]:
print(A_named)
a = ACN(A_named)

print( "Length of : "+ str( len(a) ) );

[[0 2 0 0]
 [1 3 5 6]
 [0 4 0 7]]
Parent Tree: 1
2
3
4
Parent Tree: 2
1
3
5
Parent Tree: 3
1
2
4
5
Parent Tree: 4
1
3
5
Parent Tree: 5
2
3
4
6
7
Parent Tree: 6
5
7
Parent Tree: 7
5
6
Length of : 7


In [319]:
a[1].children

[<__main__.Node instance at 0x10b4ca440>,
 <__main__.Node instance at 0x10b4caa70>,
 <__main__.Node instance at 0x10b4ca8c0>,
 <__main__.Node instance at 0x10b4ca758>,
 <__main__.Node instance at 0x10b4ca680>,
 <__main__.Node instance at 0x10b4ca128>,
 <__main__.Node instance at 0x10b4ca9e0>,
 <__main__.Node instance at 0x10b4cab90>,
 <__main__.Node instance at 0x10b4ca1b8>,
 <__main__.Node instance at 0x10b4cacf8>,
 <__main__.Node instance at 0x10b429fc8>,
 <__main__.Node instance at 0x10b4ca320>,
 <__main__.Node instance at 0x10b419e60>,
 <__main__.Node instance at 0x10b419cf8>,
 <__main__.Node instance at 0x10b419d88>,
 <__main__.Node instance at 0x10b419d40>,
 <__main__.Node instance at 0x10b419488>,
 <__main__.Node instance at 0x10b2e20e0>,
 <__main__.Node instance at 0x10b4b2320>,
 <__main__.Node instance at 0x10b4b2290>,
 <__main__.Node instance at 0x10b4b2440>,
 <__main__.Node instance at 0x10b4b23f8>,
 <__main__.Node instance at 0x10b4b2050>,
 <__main__.Node instance at 0x10b4

In [320]:
print(A_named)
print("Parent Identity: "+str(a[0].identity) )
for c in a[1].children:
    print( c.identity )

[[0 2 0 0]
 [1 3 5 6]
 [0 4 0 7]]
Parent Identity: 1
<__main__.Node instance at 0x10b4242d8>
<__main__.Node instance at 0x10b4cab48>
<__main__.Node instance at 0x10b4ca950>
<__main__.Node instance at 0x10b4ca4d0>
<__main__.Node instance at 0x10b4cadd0>
<__main__.Node instance at 0x10b4ca248>
<__main__.Node instance at 0x10b4caef0>
<__main__.Node instance at 0x10b4ca170>
<__main__.Node instance at 0x10b4ca050>
<__main__.Node instance at 0x10b4cac20>
<__main__.Node instance at 0x10b4290e0>
<__main__.Node instance at 0x10b4293b0>
<__main__.Node instance at 0x10b419ef0>
<__main__.Node instance at 0x10b419ea8>
<__main__.Node instance at 0x10b419cb0>
<__main__.Node instance at 0x10b419dd0>
<__main__.Node instance at 0x10b419fc8>
<__main__.Node instance at 0x10b4193b0>
<__main__.Node instance at 0x10b4b25f0>
<__main__.Node instance at 0x10b4b2248>
<__main__.Node instance at 0x10b4b2488>
<__main__.Node instance at 0x10b4b23b0>
<__main__.Node instance at 0x10b4b2368>
<__main__.Node instance at 

In [295]:
print(B_named )

maxCols = 3
maxRows = 2

for col in range( maxCols ):
        for row in range( maxRows ):
            print( B_named[row,col] )
            

[[0 2 4]
 [1 3 0]]
0
1
2
3
4
0


In [294]:
a[0].children

[<__main__.Node instance at 0x10b429128>,
 <__main__.Node instance at 0x10b4294d0>,
 <__main__.Node instance at 0x10b429e60>,
 <__main__.Node instance at 0x10b429638>,
 <__main__.Node instance at 0x10b4299e0>,
 <__main__.Node instance at 0x10b4f7758>,
 <__main__.Node instance at 0x10b43fbd8>,
 <__main__.Node instance at 0x10b43f6c8>,
 <__main__.Node instance at 0x10b43fb90>,
 <__main__.Node instance at 0x10b43f5f0>,
 <__main__.Node instance at 0x10b43fc20>,
 <__main__.Node instance at 0x10b43fe18>,
 <__main__.Node instance at 0x10b43f830>,
 <__main__.Node instance at 0x10b43f2d8>,
 <__main__.Node instance at 0x10b43fa70>,
 <__main__.Node instance at 0x10b43fd40>,
 <__main__.Node instance at 0x10b43f7e8>,
 <__main__.Node instance at 0x10b43f908>,
 <__main__.Node instance at 0x10b43fa28>,
 <__main__.Node instance at 0x10b43f710>,
 <__main__.Node instance at 0x10b443950>,
 <__main__.Node instance at 0x10b41a1b8>,
 <__main__.Node instance at 0x10b41ab90>,
 <__main__.Node instance at 0x10b4

In [188]:
range(2)

[0, 1]

In [24]:
B_named.shape

(2, 3)

In [36]:
produceGraphs1( B_named )

[[0]]
[[1]]
[[2]]
[[3]]
[[4]]
[[0]]


In [34]:
print(B_named
     )

[[0 2 4]
 [1 3 0]]


In [35]:
print(A_named)

[[0 2 0 0]
 [1 3 5 6]
 [0 4 0 7]]


In [63]:
A_named[1,0]

1

In [38]:
a.append(3
        )

In [39]:
a


[3]

In [152]:
a = 1
a+= 1

In [41]:
Nil

NameError: name 'Nil' is not defined

In [56]:
not True

False